BlockEQ.xcodeproj/project.pbxproj
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.xib
BlockEQ/Views/KeyboardView.swift
BlockEQ/Views/KeyboardView.xib

* Removes "next" button from PinViewController
* Adds a reusable custom / configurable KeyboardView class
* Simplifies PinEntryViewController completion logic
Part 1 of #37 
This PR creates a new, reusable `KeyboardView` that can be dropped in anywhere. 
It also replaces the `UITextField` on the `PinViewController`, with the new `KeyboardView`.

[BOUNTY] Redesigned pin entry view controller (part 1/3)

---

BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Utils/KeychainHelper.swift
BlockEQ/Utils/PinOptionHelper.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/MnemonicViewController.swift

Normal
N/A
This corrects the "clear wallet" functionality when selecting that option from the settings screen.

[FIX] Corrects "Clear Wallet" behaviour

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Utils/KeyboardHelper.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.swift
BlockEQ/Views/KeyboardView.swift

Normal
This allows the user to cancel the "clear wallet" if they change their mind when entering their PIN. Same for viewing the mnemonic.

[FIX] Adds support to cancel pin entry on clearing wallet / viewing mnemonic

---

BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/View Controllers/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.swift
BlockEQ/View Controllers/WalletViewController.swift

Normal
N/A
This allows the user to cancel the "Require PIN" challenge, and restore the prior setting if it does get cancelled.
1. Create a wallet and set a PIN
2. Go to the settings menu and select "Require PIN" to disable PIN entry
3. The keyboard should pop up
4. Hit "cancel" (bottom left)
5. The "Require PIN" option should **still be enabled**
6. The app should still prompt for PINs when opening / trading / viewing mnemonic, etc.

[FIX] Corrects issue when disabling PIN requirement and cancelling PIN entry

---

BlockEQ/View Controllers/WalletViewController.swift

Normal
N/A
This fix corrects an array index crash that can occur when a query to the Stellar network could fail to populate assets in the wallet.

[FIX] Quick fix when a network request fails, and assets.count is zero

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
BlockEQ/Info.plist

Normal
Re-adds the mistakenly removed project file entry for AppIcon asset catalog.
**NOTE:** It looks red in the screenshot above, but works when deployed to a device.

[FIX] Corrects asset catalog use in project file

---

BlockEQ/Objects/StellarAsset.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Menus/WalletSwitchingViewController.swift
BlockEQ/Views/Cells/WalletItemActivateCell.swift
BlockEQ/Views/Cells/WalletItemCell.swift

Normal
This PR addresses the user experience of the assets currently managed by the wallet, by not allowing the user to remove the asset if the balance is greater than zero.
This prevents the user from encountering a confusing error prompt.
This refactors the `WalletItemCell`, and `WalletItemActivateCell` class to use a `ViewModel` pattern to help move towards being able to eventually snapshot test our cells.

[FEATURE] Hides the "Remove Asset" button when balance is above 0

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Extensions/Price+Extensions.swift
BlockEQ/Operations/TradeOperation.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

Normal
This PR corrects behaviour when inputting large amounts into the trade fields.
It refactors the `TradeOperation` to directly accept a Stellar `Price` object, which simplifies logic inside the operation.
In addition to updating the `TradeOperation`, I've added an extension `Price+Extensions.swift` to the `Price` object to manage conversion and overflow checking, that is possible as a result of the issue here: https://github.com/Soneso/stellar-ios-mac-sdk/pull/32.
N/A

[FIX] Corrects the ability to enter invalid trade amounts

---

BlockEQ/Extensions/String+DecimalFormatter.swift
BlockEQ/Objects/StellarAsset.swift
BlockEQ/Objects/StellarEffect.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/OrderBookViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/WalletViewController.swift

Normal
This PR updates the `TradeViewController` to read the available balance if the from trade asset is native.
It also removes usage of `Float` for currency conversion, preferring `Double`. It also uses the new `NumberFormatter` class to specify exact formatting rules (which will be helpful for localization later)
Addresses #78 
* Codifies rounding rules with new NumberFormatter

[FIX] Updates TradeViewController to display available asset balance for XLM

---

Podfile
Podfile.lock

Low
Use a fork of the pod `Whisper` to remove Swift 4.2 warnings, and pointed `SCLAlertView` pod at master branch of its repo.

Updated Podfile to add forks of pods for full Swift 4.2 support

---

BlockEQ/Resources/Info.plist

Low
Enters a plist entry so we don't have to repetitively indicate export compliance settings.
N/A
N/A

Updates plist to support not entering export compliance in AppStore Connect

---

BlockEQ/Extensions/Price+Extensions.swift
BlockEQ/Extensions/String+DecimalFormatter.swift
BlockEQ/Objects/StellarEffect.swift
BlockEQ/Operations/TradeOperation.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Resources/Info.plist
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
Podfile
Podfile.lock

High
This PR corrects the truncation of decimals after the Soneso SDK was updated to only accept `Int32` parameters in the `Price` object.
It also adds a confirmation prompt when trading, so the user has an additional confirmation step.
The way this was fixed progressively scales the `numerator` and `denominator` to take the `max()` of the exponent of either value, and finding the maximum value we can scale the numerator and denominator by without overflowing the 32-bit integers used in the `Price` object.

[FIX] Corrects decimal truncation of trade offers

---

BlockEQ/Operations/PaymentTransactionOperation.swift
BlockEQ/View Controllers/P2P/AddPeerViewController.swift
BlockEQ/View Controllers/Wallet/AddAssetViewController.swift
BlockEQ/View Controllers/Wallet/WalletSwitchingViewController.swift

Normal
This PR changes the requirement of a non-optional `limit` parameter on any `ChangeTrustOperation`. Since https://github.com/Soneso/stellar-ios-mac-sdk/commit/5ccef638b90925354a628ef42b0934c5f92e8f92 was recently implemented, we no longer require this parameter to any of our operations.
N/A

[FIX] Remove required parameter for trust limit on 'ChangeTrustOperation'

---

BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
StellarAccountService/Services/StellarAccountService+Internal.swift
StellarAccountService/Services/StellarAccountService.swift

Normal
This PR corrects streaming payments by initiating an account update when a payment notification is streamed to the app.
This doesn't append the received operation and its effects to the existing account as a minimal update to the account.
I opted to trigger a fetch of the user's account again in order to recalculate available balance, minimum balances, etc...

[FIX] Streaming payment support

---

BlockEQ/Objects/StellarEffect+Extensions.swift
StellarAccountService/Objects/StellarEffect.swift
StellarAccountService/Operations/Account/FetchAccountEffectsOperation.swift
StellarAccountService/Operations/Account/FetchTransactionsOperation.swift
StellarAccountService/Operations/Trade/FetchOffersOperation.swift

High
This PR corrects the treatment of trading effects in the `WalletViewController`. Effects are now fetched from `now - 200` records.

[FIX] Representing trades properly in effect history

---

BlockEQ/Data Sources/WalletTableViewDataSource.swift
StellarAccountService/Objects/StellarOffer.swift
StellarAccountService/Operations/Trade/FetchOrderBookOperation.swift

High
This PR corrects an issue when serializing `StellarOrderResponse` objects to `StellarOrderbookOffer`, which was causing incorrect data to show in the order book.

[FIX] Incorrect data in order book

---

BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Data Sources/WalletSwitchingTableViewDataSource.swift
BlockEQ/Data Sources/WalletTableViewDataSource.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Wallet/InflationViewController.swift
BlockEQ/View Controllers/Wallet/WalletSwitchingViewController.swift

High
This PR corrects a poor UX choice in simply shaking the inflation destination field when it was either:
1) Your own account
2) The account you've already set the inflation destination to
Now, a prompt indicating the problem has been implemented to better inform the user as to what's wrong.
* Reorganize delegation structure for inflation setting

[FIX] Better prompt when updating the inflation destination

---

BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/View Controllers/Security/BlankAuthenticationViewController.swift
BlockEQ/View Controllers/Security/PinViewController.swift

Low
Removing deprecated usage of setting global `UIStatusBarStyle`.

[FIX] Correct warnings relating to UIStatusBarStyle

---

BlockEQ/Data Sources/WalletSwitchingTableViewDataSource.swift
BlockEQ/Extensions/String+DecimalFormatter.swift
BlockEQ/Objects/StellarAsset+Extensions.swift
BlockEQ/View Controllers/Address Book/SelectAssetViewController.swift
BlockEQ/View Controllers/P2P/TrustedPartiesViewController.swift
BlockEQ/View Controllers/Trade/BalanceViewController.swift
BlockEQ/View Controllers/Wallet/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet/SendViewController.swift

Normal
Around the application - there are places where it's not clear why you can't remove an asset when the displayed amount balance is `0.00`, when the amount is actually low like `0.000001987`.
To address this, we now display `< 0.0001` for amounts below the minimum amount threshold.

[FIX] Displays '< 0.0001' for small amounts of assets

---

BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
StellarAccountService/Services/StellarTradeService.swift

High
This PR increases the rate at which the offers screen is updated, by immediately requesting an update when a trade is successfully posted.
N/A

[FIX] Speeds up the refreshing of a user's offers when posting a trade

---

BlockEQ/Data Sources/WalletSwitchingTableViewDataSource.swift
BlockEQ/Extensions/String+DecimalFormatter.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Address Book/SelectAssetViewController.swift
BlockEQ/View Controllers/P2P/TrustedPartiesViewController.swift
BlockEQ/View Controllers/Trade/BalanceViewController.swift
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/OrderBookViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet/SendViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift

High
While correcting the behaviour of the order book, I noticed the currently released app on the App Store had a lot of values as 0.00 in order rows. This is hard to read and understand the listed value of the offer, so this PR introduces a new decimal format for the order book in order to address this issue.
**Decimal formatted:** To be used in small cells where there's not a lot of 
**Trade formatted:** To be used for high-precision display of crypto amounts
**Trade formatted strings:**
-> Minumum decimals: 2
-> Maximum decimals: 8
**Display formatted strings:**
-> Minumum decimals: 2
-> Maximum decimals: 4

[FIX] Using a new decimal format for trades in the order book with more precision

---

BlockEQ/Objects/StellarAccount+Extensions.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Trade/BalanceViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet/SendViewController.swift
StellarAccountService/Objects/StellarAccount.swift

Normal
Updates usage of the formatted available balance on the `BalanceViewController` to be able to display more decimal precision.
Also converts some usage of double precision types to `Decimal` to remove some redundant conversions around the app.
* Also converts usage of lower-precision Double to Decimal

[FIX] Corrects available balance display to show untruncated amounts

---

BlockEQ/View Controllers/Wallet/InflationViewController.swift
StellarAccountService.xcodeproj/project.pbxproj
StellarAccountService/Objects/StellarAccount+Operations.swift
StellarAccountService/Objects/StellarAccount.swift
StellarAccountService/Protocols.swift
StellarAccountService/Services/StellarAccountService.swift
StellarAccountService/Services/StellarCoreService.swift
StellarAccountService/Services/StellarP2PService.swift
StellarAccountService/Services/StellarTradeService.swift
StellarAccountService/StellarConfig.swift
StellarAccountService/Utilities/SecretManager.swift
StellarAccountServiceTests/Objects/StellarAccountOperationTests.swift
StellarAccountServiceTests/TestObjects.swift

Low
This PR has some minor structural updates and adds more protocols in order to be able to write mock and stub objects within the `StellarAccountService`.
Writing mock / stub objects allows us to only test local segments of code, without having to initialize an entire set of interconnected & related objects.
N/A
* Creates TestObjects and minor refactor to make stubbing / mocking easier

[FEATURE] Adds some tests for StellarAccount+Operations

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Data Sources/WalletSwitchingDataSource.swift
BlockEQ/Data Sources/WalletTableViewDataSource.swift
BlockEQ/View Controllers/Wallet/WalletSwitchingViewController.swift

High
This PR fixes a crash that occurs when removing the asset that the wallet is currently switched to. It now does an out-of-bounds check, and also switches the wallet back to the native asset when this case occurs.
N/A
* Remove optional index
* Make native asset selected when removing currently selected asset

[FIX] Corrects a crash when removing an asset from the users wallet

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Data Sources/TradePickerDataSource.swift
BlockEQ/Data Sources/WalletDataSource.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Trade/OrderBookViewController.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift
StellarAccountService/Objects/StellarAccount.swift
StellarAccountServiceTests/Objects/StellarAccountTests.swift

Normal
This PR updates the trade selectors in the `TradeViewController` to use data sources for each picker. 
This allows us to refresh them more consistently in order to fix a bug when adding an asset in the `TradeViewController` when no assets other than lumens are available on the user's account.

[FIX] Trade selectors not being populated after adding asset in trade view

---

BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/Data Sources/TransactionDetailsDataSource.swift
BlockEQ/View Controllers/Transactions/TransactionDetailsViewController.swift
BlockEQ/Views/Transactions/TransactionDetailsCell.swift
BlockEQ/Views/Transactions/TransactionDetailsCell.xib

Normal
This PR corrects a missing translation for a format string on the memo field, updates the copy data messaging, and integrates the amount for each effect into the `TransactionDetailsCell`

[FIX] Missing fields / translations in TransactionDetailsCell

---

BlockEQ/View Controllers/Application/AppTabController.xib

High
This PR corrects a layout issue in `AppTabController` that was causing incorrectly-sized layouts for iPad and iPhone Xr.

[FIX] Corrects UITabBar issue for iPhone Xr

---

BlockEQ/View Controllers/Trade/TradeViewController.swift

Normal
This PR corrects selection in the asset selectors in the `TradeViewController`. 
If the previously selected asset still exists in the datasource, it's reselected. Otherwise, the picker selects the first asset available in its respective data source.

[FIX] Trade selectors now intelligently select the previous asset if possible

---

BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Extensions/UIView+Autolayout.swift
BlockEQ/Objects/Diagnostic+Extensions.swift
BlockEQ/Objects/Diagnostic.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Diagnostics/DiagnosticViewController.swift
BlockEQ/Views/Cells/Diagnostics/DiagnosticCompletedCell.swift
BlockEQ/Views/Cells/Diagnostics/DiagnosticCompletedCell.xib
BlockEQ/Views/Cells/Diagnostics/DiagnosticDataCell.swift
BlockEQ/Views/Cells/Diagnostics/DiagnosticDataCell.xib
BlockEQ/Views/Cells/Diagnostics/DiagnosticInputCell.swift
BlockEQ/Views/Cells/Diagnostics/DiagnosticInputCell.xib

Normal
This PR automatically initializes `AppDiagnostic` when creating a `Diagnostic` object. This allows the app diagnostic screen to have hardware info / os version / app info, etc.
It also converts the `UICollectionViewCell`s for diagnostics into self-sizing cells so that they expand to the height they need to look better on tall devices, and still work on the iPhone 5S / SE.

[FIX] Adds app diagnostics, and makes battery state an optional field

---

BlockEQ/Resources/Info.plist
StellarAccountService/Services/StellarIndexingService.swift

High
This PR corrects a crash when progressively updating the index due to not dispatching the update on the main thread and then trying to access the resultant objects.
N/A

[FIX] Crash when indexing when running on a hardware device

---

StellarAccountService/Objects/StellarEffect.swift
StellarAccountService/Objects/StellarOperation.swift
StellarAccountService/Objects/StellarTransaction.swift
StellarAccountService/Services/StellarIndexingService.swift

High
This PR converts the objects `StellarTransaction`, `StellarOperation`, and `StellarEffect` to be structs in order to pass them by value.
This allows us to use them in the `StellarDataGraph` which gets built on a background thread. This helps us avoid running into crashes when trying to access objects across thread boundaries.
N/A

[FIX] Updates StellarIndexingService to fully run in background

---

BlockEQ/Objects/StellarOperation+Extensions.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
StellarAccountService/Objects/StellarOperation.swift
StellarAccountService/Operations/Account/FetchOperationsOperation.swift

High
This PR adds more details into the `StellarOperation` struct so that it can be displayed in the `TransactionDetailsViewController`
Ideally, we would write wrapping subclassed types for `OperationResponse`, but I want to keep `StellarOperation` as a value type. This obviously has some implications since we have to check the type of operation at runtime instead of compile time, but it's useful to allow these objects to be passed across threads by value.

[FEATURE] Added ability to store specific operation data in a StellarOperation

---

BlockEQ/View Controllers/Trade/TradeViewController.swift

High
This PR corrects the behaviour of the trade selectors. The rules are as folllows:
* All assets should be available in the 'from' list, at all times
* All assets excluding the currently selected 'from' asset should be in the 'to' list.
* When you select any item in the 'to' list, the 'from' option is not modified.
* When you select any item in the 'from' list, the 'to' option is not modified.
* _Unless_ it's the current 'to' item. In that case, the first asset in the 'to' list is selected.

[FIX] Corrects behaviour with selecting assets in the trade view

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Wallet.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Transactions/TransactionDetailsViewController.swift

High
This PR updates the view controller to immediately push the `TransactionDetailsViewController` onto the view stack even before indexing is finished. It then responds to the `indexingFinished()` delegate callback to update the view.
After the first time transactions details are viewed and indexed, there is no loading time for other rows.

[FIX] Show Transaction Details immediately when cell is tapped

---

BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/AddressCoordinator.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Data Sources/ContactsDataSource.swift
BlockEQ/Data Sources/TransactionDetailsDataSource.swift
BlockEQ/Data Sources/WalletDataSource.swift
BlockEQ/Objects/StellarAddress+Extensions.swift
BlockEQ/View Controllers/Transactions/TransactionDetailsViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.xib
BlockEQ/Views/Cells/TransactionHistoryCell.swift
StellarAccountService/Operations/Account/FetchOperationsOperation.swift
StellarAccountService/Operations/Account/FetchTransactionsOperation.swift
StellarAccountService/Operations/Misc/NodeIndexingOperation.swift
StellarAccountService/Services/StellarIndexingService.swift

High
This PR fixes issues surrounding not being able to view the details of certain trade transactions. 
Because some trades don't affect the source account the user is viewing (depending on the trade, the `source account` affects the other account traded with), it's impossible for us to know how to connect the effects to an operation, to finally find the transaction to display. As a result, we have to disable viewing the details of trade transactions that we won't be able to resolve.
Trade effects are *not* selectable anymore, and will not highlight when tapped.
This PR also corrects:
* Always allowing bouncing on `UICollectionView` despite no scroll view content
* Not being able to navigate back from the transaction details screen when loading is in progress
* Improved edge indexing …

[FIX] Trade transaction details

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Utils/Reachability.swift

Normal
This PR implements an iOS 11 and iOS 12 wrapper class that detects changes in network connectivity.
In [WWDC Session 715](https://developer.apple.com/videos/play/wwdc2018/715/), Apple strongly recommended moving away from `SCNetworkReachability`, where possible.
This class begins the transition for this by providing a simple wrapped interface to reachability, that switches depending on platform support for `NWPathMonitor`
N/A
Any additional notes, implications, caveats...

[FEATURE] Network Reachability wrapper class

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Extensions/UIAlertController+Prompts.swift
BlockEQ/Extensions/UIViewController+AdvancedSecurity.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.xib
BlockEQ/View Controllers/Wallet/VerificationViewController.swift
BlockEQ/View Controllers/Wallet/VerificationViewController.xib
StellarAccountService.xcodeproj/project.pbxproj
StellarAccountService/Objects/StellarMnemonicPassphrase.swift
StellarAccountService/Services/StellarAccountService.swift
StellarAccountServiceTests/Objects/StellarMnemonicPassphraseTests.swift

High
This PR adds support for the mnemonic passphrase when creating and restoring a wallet.
Like our other wallets, it presents two prompts that ask the user to enter then confirm their mnemonic passphrase.

[FEATURE] Recovery mnemonic passphrase

---

BlockEQ/Data Sources/WalletDataSource.swift

High
This PR corrects behaviour after the refactor that filtered out any effect whose base type didn't match what the wallet was currently viewing.
Since trades also might reference a non-native token, we have to include the buying / selling asset of the asset pair in the filtering logic in order to not exclude them.

[FIX] Missing Trade effects for non-native assets in effect list

---

BlockEQ/Extensions/UIViewController+AdvancedSecurity.swift
BlockEQ/Resources/Base.lproj/Localizable.strings

Normal
This PR adds a notification when a passphrase could not successfully be created from their input text.

[FIX] Adds a prompt that notifies the user when a disallowed passphrase was entered

---

BlockEQ/Extensions/UIAlertController+Prompts.swift
BlockEQ/Extensions/UIViewController+AdvancedSecurity.swift

Normal
This PR conceals the text entry when typing a mnemonic passphrase.
Any additional notes, implications, caveats...

[FIX] Conceals mnemonic passphrase during text entry

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift

Normal
This PR updates the `MnemonicViewController` to be able to conceal the 'advanced security' button. This avoids inadvertently seeing it when viewing the secret mnemonic phrase.
N/A
Any additional notes, implications, caveats...

[FIX] Adds ability to hide the advanced security button

---

BlockEQ/View Controllers/Wallet/MnemonicViewController.swift

Normal
This PR temporarily removes the prompt indicating successful storage of the user's secret in the keychain.
Until Apple's `SecAddSharedWebCredential` sends an error back in the callback when tapping 'Don't Allow', this will need to stay disabled.

[FIX] Removes the success prompt from saving a mnemonic to the keychain

---

BlockEQ/Data Sources/WalletDataSource.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift
BlockEQ/Views/Cells/TransactionHistoryCell.swift

Normal
The account details for "Account Created" will never work because the source account for the transaction will be the account who sent the Lumens to your account. This means when the account transactions are fetched from Horizon, the necessary transaction details will not be sent along with the response.
The solution is to disable details for "Account Created" until we have a more robust data fetching system.

[FIX] Selecting 'Account Created' effect does not load

---

BlockEQ/Data Sources/WalletDataSource.swift

High
This PR corrects behaviour introduced in `2.4.0` that allowed trades to show for each of the buying and selling asset. 
Unfortunately, this also included effects for assets which you weren't currently filtering. This is now corrected.
N/A

[FIX] Incorrect effects appearing in wallet list for other assets

---

StellarAccountService/Services/StellarAccountService+Internal.swift

Normal
This PR removes the requirement that the app has secret keys for the current account. This helps during debugging mode to view wallets as a read-only without private signing keys.
N/A

[FIX] Removes the requirement that secrets are present for accounts in StellarAccountService during initialization

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Extensions/UIViewController+Blurrable.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Keys/SecretSeedViewController.swift
BlockEQ/View Controllers/Keys/SecretSeedViewController.xib
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.xib

Normal
This PR adds support to blur the user's mnemonic just as it's done for the secret seed. This prevents over-the-shoulder glances if the user is in a public space and navigates into the "view mnemonic" screen.

[FEATURE] Adds support to blur the user's mnemonic words

---

BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift

Normal
This PR adds support to run tasks in the `ApplicationCoordinator` when the application lifecycle event for becoming active is triggered.
In `ApplicationCoordinator` when the app becomes active, we now trigger a refresh of the account information.
N/A

[FIX] Forces the account information to be refetched when the application becomes active

---

BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Wallet/AddAssetViewController.swift

Normal
This PR addresses an issue where it's possible to add a trust line to your own account. 
There's no case where an issuing address for an asset would want to add a trust line to its self, so we're preventing that action when allowing the user to create trustlines.
Additionally - When you punch in an invalid issuer for an asset + address combination, we display a general error message for any Stellar network error flagged with `bad_request`.

[FIX] Prevents users from adding an asset trustline to their own account address

---

BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
StellarHub/Services/Streaming/StreamService.swift

Normal
This PR removes open streams when background and re-creates them when foregrounding the application.
N/A

[FIX] Suspend and restore streaming connections when foregrounded and backgrounded

---

StellarHub/Services/StellarIndexingService.swift

Normal
This PR adds a bit of logic to prevent multiple indexing operations from getting added to the processing queue. 
This could happen as a result of the `IndexingService` trying to update the index after receiving a callback for each type of object: `StellarOperation`, `StellarTransaction`, and `StellarEffect`.
N/A
* This could happen as a result of updating each type of Stellar object

[FIX] Added some checks to prevent an indexing operation to be started multiple times

---

BlockEQ/Views/Transactions/TransactionSection.swift

High
This PR corrects a crash that tries to load a section footer instead of a header for transaction details in development builds.
N/A

[FIX] Corrects a crash when viewing transaction details

---

BlockEQ/View Controllers/Wallet/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet/SendViewController.swift
StellarHub/Objects/StellarAccount.swift
StellarHubTests/Objects/StellarAccountTests.swift

High
This PR incorporates the missing network fee when displaying the available balance to the user. It also now does the calculation on behalf of the user when validating the sent amount.
Sending 100% of your available balance for an asset now succeeds, and leaves no residual amounts.

[FIX] Sending 100% of an available asset now incorporates network fee

---

BlockEQ/Data Sources/TradeAssetListDataSource.swift

Normal
This PR implements a minor fix to use `contentInset` instead of the old method of computing cell widths using `sectionInset` for the `TradeAssetListDataSource`.

[FIX] Corrects usage of content inset instead of section inset in the trading asset datasource

---

BlockEQ.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Normal
This PR incorporates two new cocoa pods: 
* [Cache](https://github.com/hyperoslo/Cache)
* [Imaginary](https://github.com/hyperoslo/Imaginary)
These two pods are meant to offer caching abilities for `Codable` objects (eventually), as well as for image asset icons for the new asset lists.
N/A

[FEATURE] Adds 'Imaginary' and 'Cache' dependencies

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ.xcodeproj/xcshareddata/xcschemes/BlockEQ.xcscheme
BlockEQ/Views/Asset/AssetHeaderView.swift
BlockEQ/Views/Cells/Assets/AssetActionCell.swift
BlockEQ/Views/Cells/Assets/AssetAmountCell.swift
BlockEQ/Views/Cells/Assets/AssetIssuerCell.swift
BlockEQ/Views/Cells/Assets/AssetManageCell.swift
Podfile
Podfile.lock
StellarHub.xcodeproj/project.pbxproj
StellarHub.xcodeproj/xcshareddata/xcschemes/StellarHub.xcscheme

Normal
This PR corrects behaviour where the [Imaginary](https://github.com/hyperoslo/Imaginary) dependency would set the placeholder image on the `UIImageView` before checking to see if there was already a cached copy.
Upstream issue: https://github.com/hyperoslo/Imaginary/issues/88
Upstream PR: https://github.com/hyperoslo/Imaginary/pull/89

[FIX] Flickering asset icons by updating dependencies

---

BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Views/Cells/OrderBookEmptyCell.swift

Low
This PR properly allows the empty cell to load when there are no posted offers. Also updates the text to be localized.

[FIX] Missing cell when viewing offers when none posted

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Extensions.swift
StellarHub/Protocols.swift
StellarHub/Services/Account/AccountUpdateService.swift
StellarHub/Services/StellarIndexingService.swift
StellarHubTests/Services/AccountUpdateServiceTests.swift

Normal
This PR updates the streaming service to restart for an account when it is funded for the first time. It also decreases the amount of time between manual fetches for account data.

[FIX] Restart streams for account upon new account funding

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator+Wallet.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Operations/CacheAccountQROperation.swift
BlockEQ/Utils/CacheManager.swift
BlockEQ/Utils/QRMap.swift
BlockEQ/View Controllers/Wallet/ReceiveViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.xib
StellarHub/Services/Account/AccountUpdateService.swift

Normal
After some discussion with @dabitdev about the empty state for the wallet when newly created - he suggested a good UX improvement to display a QR code to fund the wallet without having to hit "receive". This makes so much more sense.
Since we already had a QR code for the account when created, it wasn't much work to swap out the large wallet icon for the QR code.

[FEATURE] Display QR code in new account state

---

BlockEQ/Coordinators/AssetCoordinator.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Assets/AssetListViewController.swift
BlockEQ/View Controllers/Wallet/InflationViewController.swift
Podfile
StellarHub/Operations/Account/UpdateInflationOperation.swift
StellarHub/Protocols.swift
StellarHub/Services/Account/AccountManagementService+Operations.swift
StellarHubTests/TestObjects.swift

High
This PR moves the presentation and dismissal of alerts, view controllers, etc. when updating the inflation destination. 
This avoids accessing view controllers when they've already been deallocated.

[FIX] Corrects crash when setting / clearing inflation destination

---

BlockEQ/Coordinators/AuthenticationCoordinator.swift
BlockEQ/View Controllers/Security/PinViewController.swift
BlockEQ/Views/Cells/Settings/SettingsSwitchCell.swift

Normal
This PR moves the Authentication view controllers to also be lazily instantiated, so that they may be reset and re-used multiple times. This is to correct an issue where the authentication challenge was not being presented in some cases.
N/A

[FIX] Authentication challenges not being displayed in some cases

---

BlockEQ/Coordinators/TradingCoordinator.swift

Normal
This PR corrects an issue where the initial asset pair in the order book was XLM / XLM until the first refresh occurred.

[FIX] Initial asset pair in orderbook is XLM / XLM

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/AssetCoordinator.swift
BlockEQ/Coordinators/PaymentCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Data Sources/AccountAssetListDataSource.swift
BlockEQ/Data Sources/ConcreteAssetListDataSource.swift
BlockEQ/Data Sources/TradeAssetListDataSource.swift
BlockEQ/View Controllers/Keys/SecretSeedViewController.swift
BlockEQ/View Controllers/Wallet/AddAssetViewController.swift

Normal
This PR refactors the `AssetListDataSource` protocol so that shared code can be pulled into a concrete subclass of `NSObject`, and extended for both the `TradeAssetListDatasource` and `AccountAssetListDataSource`

[FIX] Refactor AssetListDataSource so shared logic can be used by TradeAssetListDataSource

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Wallet.swift
BlockEQ/Coordinators/AssetCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Data Sources/TradeAssetListDataSource.swift
BlockEQ/Extensions/UIViewController+AdvancedSecurity.swift
BlockEQ/View Controllers/Assets/AssetListViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

Normal
This PR makes it a nicer UX when you are adding an asset for the first time in the Trade screen, by either displaying 1 or two sections, depending on which assets currently have trustlines on the account.
* You can no longer remove assets from the trade screen, doing so doesn't make sense
* Smart selection for when to display available assets as a separate section

[FIX] This corrects some behaviour when adding assets via Trade

---

BlockEQ/Coordinators/AssetCoordinator.swift

Normal
Adds the error message to the action when the user taps the `+` on an`AssetManageCell`

[FIX] Displays the low balance error when adding an asset via the green +

---

BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.swift
BlockEQ/Views/TradeHeaderView.swift

Low
This PR corrects a small UX bug where you could switch segments when trading when no assets were added.

[FIX] Prevents trade segments from switching when no assets added

---

BlockEQ/View Controllers/Wallet/WalletViewController.swift

Low
When the view controller is first loaded, the default XIB information set in text fields. If the account fails to update, this data is not meant to be left in the initial state, and should be updated to reflect what the app is doing.
* This issue was reported by one of our users after recovering via iCloud (which does not transfer the user's keychain information to the new device). Some work will have to be done to make that iCloud restore experience less confusing.

[FIX] Correct missing localization key for new account

---

BlockEQ.xcodeproj/xcshareddata/xcschemes/BlockEQ.xcscheme
BlockEQ/Coordinators/Application/ApplicationCoordinator+AccountExtensions.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
StellarHub/Services/Streaming/StreamService.swift

Urgent
This PR corrects an unintended number of updates from being requested from the Horizon API when streaming objects are returned from the `StreamingService` and stream objects from the Soneso SDK.
N/A

[FIX] Prevent account from updating an unreasonable number of times when stream updates received

---

BlockEQ/Coordinators/AuthenticationCoordinator.swift

Normal
This PR corrects a recently-introduced bug where the authentication system would reset the wallet due to the number of failed PIN attempts not being cleared when the authentication challenge was reset.
N/A

[FIX] Corrected issue not resetting failed pin attempts when authentcation was dismissed

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Debug.swift
StellarHub.xcodeproj/project.pbxproj
StellarHub/Protocols.swift
StellarHub/Services/IndexingService.swift

Normal
This PR moves recording the last index account hash to when the operation completes. This allows indexing to run after operations, transactions and effects are fetched.
N/A

[FIX] Corrects indexing from being run due to recording the completion too early

---

BlockEQ/View Controllers/Application/AppTabController.xib

Normal
This PR corrects the top constraint in the AppTabController to be pinned to the superview instead of the safe area. This allows sub view controllers to take the full height of the screen (including the nav bar).
Child VCs can still avoid the navigation bar or the top area on notched devices by respecting the safe area layout margin.
N/A

[FIX] Correct top area constraint on AppTabController

---

BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.swift
BlockEQ/Views/TradeHeaderView.swift
Podfile

Normal
This PR removes the Whisper notification from the trading screen. Since iOS introduced large titles, the Whisper library isn't playing nicely with them. 
I spent way too much time trying to offset the whisper library to work correctly. Rather than blowing more time on this to correct the content inset, I'm switching the Trade notification to use a simple `MBProgressHud` text instead. See attached screenshot.

[FIX] Corrects the location of the Whisper notification on the trading screen

---

BlockEQ/BlockEQWallet.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
CHANGELOG.md
StellarHub/Services/CoreService.swift
StellarHub/Services/IndexingService.swift

Normal
This PR corrects an issue of the PIN challenge being disabled for trading. It originally was implemented, but must have been stomped in a refactor.
This also adds back a call to `start()` when resetting the wallet. This was preventing an account from being re-indexed when the wallet was switched.
N/A

[FIX] PIN prompt when trading, core reset when switching wallets

---

BlockEQ/View Controllers/Address Book/StellarContactViewController.swift

Low
Corrects an issue where the name was being cleared after scanning a QR code when adding an address for a new contact.
N/A

[FIX] Correct name clearing when scanning QR code

---

BlockEQ/View Controllers/Address Book/ContactsViewController.swift
BlockEQ/View Controllers/Address Book/StellarContactViewController.swift

Low
This PR corrects an occasional issue where the `viewWillAppear` method finishes before the data source callback can complete. This leads to the contact list updating without first building the data source.
N/A

[FIX] Correct contact list not always showing the contact after being added

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Resources/Info.plist

Normal
This version bump is paired with (local) manual changes to the underlying Soneso SDK. 
Those changes have also been submitted in [a PR to the SDK](https://github.com/Soneso/stellar-ios-mac-sdk/pull/45), but are not yet accepted at the time of this PR.
We can't let the wallet sit unusable for too long, so we're choosing to release a hotfix before they've been officially corrected.
Since these SDK changes are made locally in my pods project, the commit with this PR will still fail on development builds made until the noted PR above is merged. Builds made after the PR is merged will not encounter the issue.

[FIX] Bump the version for a manual build
