BlockEQ/View Controllers/Wallet Creation and Restoration/VerificationViewController.swift
BlockEQ/View Controllers/WalletViewController.swift

*Added payment streaming.
*Updated verification to not go back to mnemonic.

Payment streaming

---

BlockEQ/View Controllers/LaunchViewController.xib
BlockEQ/View Controllers/WalletViewController.xib
BlockEQ/Views/Cells/WalletCell.xib

* Fixed typo for Stellar short hand. 
* Updated paging indicator to not show for a single wallet.

Typo fix + Paging indicator update

---

BlockEQ/Objects/PaymentTransaction.swift
BlockEQ/Utils/Constants.swift
BlockEQ/View Controllers/WalletViewController.swift
BlockEQ/Views/Cells/TransactionHistoryCell.swift
BlockEQ/Views/Cells/TransactionHistoryCell.xib

Added transaction display colours to show transaction types.

Visual Transaction Display

---

BlockEQ/View Controllers/WalletViewController.swift
BlockEQ/View Controllers/WalletViewController.xib

Added polling to wallet view controller to check for newly funded accounts.

Polling for newly funded accounts.

---

BlockEQ/Utils/KeychainHelper.swift
BlockEQ/View Controllers/LaunchViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/MnemonicViewController.xib
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/VerificationViewController.swift
BlockEQ/View Controllers/Wallet Creation and Restoration/VerificationViewController.xib
BlockEQ/View Controllers/WalletViewController.swift

* Added the ability to view your seed phrase within settings and remove the confirmation component which could hinder user experience.
* Did word correction highlighting when confirming seed phrase in wallet restoration.

Word Correction Highlighting + Simple Seed Gen

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Utils/Constants.swift
BlockEQ/View Controllers/Application/ContainerViewController.swift
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/MyOffersViewController.xib
BlockEQ/View Controllers/Trade/OrderBookViewController.swift
BlockEQ/View Controllers/Trade/OrderBookViewController.xib
BlockEQ/View Controllers/Trade/TradeSegmentViewController.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.xib
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.xib
BlockEQ/Views/Cells/OffersCell.swift
BlockEQ/Views/Cells/OffersCell.xib
BlockEQ/Views/Cells/OrderBookCell.swift
BlockEQ/Views/Cells/OrderBookCell.xib
BlockEQ/Views/OrderBookHeaderView.swift
BlockEQ/Views/OrderBookHeaderView.xib
BlockEQ/Views/TradeHeaderView.swift
BlockEQ/Views/TradeHeaderView.xib

* Added all order book and my offers tableview cells and views.
* Moved all trading containers inside a scrollview so that they are horizontally scrollable.

Order book

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Extensions/String+DecimalFormatter.swift
BlockEQ/Objects/StellarAsset.swift
BlockEQ/Operations/TradeOperation.swift
BlockEQ/View Controllers/ScanViewController.swift
BlockEQ/View Controllers/ScanViewController.xib
BlockEQ/View Controllers/SendAmountViewController.swift
BlockEQ/View Controllers/SendAmountViewController.xib
BlockEQ/View Controllers/SendViewController.swift
BlockEQ/View Controllers/SendViewController.xib
BlockEQ/View Controllers/Trade/MyOffersViewController.swift
BlockEQ/View Controllers/Trade/OrderBookViewController.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.swift
BlockEQ/View Controllers/Trade/TradeSegmentViewController.xib
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.xib
BlockEQ/View Controllers/Wallet Creation and Restoration/PinViewController.xib
BlockEQ/View Controllers/Wallet Creation and Restoration/VerificationViewController.xib
BlockEQ/View Controllers/WalletViewController.swift
BlockEQ/Views/Cells/OrderBookEmptyCell.swift
BlockEQ/Views/Cells/OrderBookEmptyCell.xib
BlockEQ/Views/Cells/WalletCell.xib
BlockEQ/Views/OrderBookHeaderView.swift
BlockEQ/Views/TradeHeaderView.swift

* Added all trade operations.
* Added UI updates.

Trade operations

---

BlockEQ/Info.plist
BlockEQ/View Controllers/AddAssetViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

Fixed issue where market trading was not going through all the time including other trading bugs.

Market trading

---

BlockEQ/Info.plist
BlockEQ/View Controllers/LaunchViewController.swift
BlockEQ/View Controllers/LaunchViewController.xib
Podfile.lock

* Solves the crash when sending payments.
* Fixes the cancel typo when creating a wallet

Updated sdk

---

Podfile.lock

Normal
This PR updates the version of the [Soneso SDK](https://github.com/Soneso/stellar-ios-mac-sdk) to build with Xcode 10.

[FIX] Updates Podfile.lock to update Soneso Stellar SDK

---

.github/CONTRIBUTING.md

Normal
This PR adds contribution guidelines to the project!

Add contribution guidelines

---

.github/ISSUE_TEMPLATE.md

Low
This PR properly formats the checklist on the issue template

[FIX] Corrected checklist item with proper formatting

---

BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/View Controllers/Settings/SettingsViewController.swift

Normal
This PR addresses a crash when cancelling PIN entry when attempting to view your mnemonic.
N/A

[FIX] Crash when cancelling PIN entry

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/Extensions/UIAlertController+Prompts.swift
BlockEQ/Extensions/UIView+Autolayout.swift
BlockEQ/Objects/Exchange.swift
BlockEQ/Operations/PaymentTransactionOperation.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Resources/Data/exchanges.json
BlockEQ/Utils/Strings.swift
BlockEQ/Utils/URLs.swift

Normal
This PR adds support fetching a list of exchanges from the BlockEQ public API. 
It creates a codable `Exchange` object that can quickly be deserialized from the API request, and refactors the existing `PaymentTransactionOperation` to use the updated serialization object.
N/A

[FEATURE] Adds support to fetch exchange list from BlockEQ API

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/AppDelegate.swift
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/AuthenticationCoordinator.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Objects/RecoveryMnemonic.swift
BlockEQ/Objects/SecretSeed.swift
BlockEQ/Operations/TradeOperation.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Utils/Constants.swift
BlockEQ/Utils/KeychainHelper.swift
BlockEQ/View Controllers/Address Book/ContactsViewController.swift
BlockEQ/View Controllers/Application/LaunchViewController.swift
BlockEQ/View Controllers/Keys/SecretSeedViewController.swift
BlockEQ/View Controllers/P2P/P2PTransactionViewController.swift
BlockEQ/View Controllers/P2P/P2PViewController.swift
BlockEQ/View Controllers/P2P/TrustedPartiesViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/AddAssetViewController.swift
BlockEQ/View Controllers/Wallet/InflationViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.xib
BlockEQ/View Controllers/Wallet/SendViewController.swift
BlockEQ/View Controllers/Wallet/VerificationViewController.swift
BlockEQ/View Controllers/Wallet/WalletSwitchingViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift

Normal
This PR adjust the recovery flow to add support to import a user's wallet using the 56-character secret seed.
It includes validation and highlighting rules during entry, in case the user makes an error inputting the key.
Closes #83

[FEATURE] Import wallet from secret key

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Extensions/UIAlertController+Prompts.swift
BlockEQ/Objects/RecoveryMnemonic.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Resources/BlockEQ.entitlements
BlockEQ/Resources/Info.plist
BlockEQ/Utils/AppleAutoFillProvider.swift
BlockEQ/Utils/AutoFillHelper.swift
BlockEQ/Utils/KeychainHelper.swift
BlockEQ/View Controllers/Keys/SecretSeedViewController.swift
BlockEQ/View Controllers/Misc/WebViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/VerificationViewController.swift
BlockEQTests/AutoFillHelperTests.swift
BlockEQTests/KeychainHelperTests.swift

Normal
This PR adds support for saving items to the Password AutoFill list in iCloud Keychain. This feature is provided as a convenience to users.
* Updated version to 2.3.0

[FEATURE] Add ability to save mnemonic and secret to keychain

---

BlockEQ.xcodeproj/xcshareddata/xcschemes/BlockEQ.xcscheme

Normal
Adds a shared scheme to the project file in preparation of CI integration.
N/A
N/A

Adds a shared scheme for the project

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/Data Sources/ContactsDataSource.swift
BlockEQ/Objects/StellarAddress+Extensions.swift
BlockEQ/Protocols/AccountUpdatable.swift
BlockEQ/View Controllers/Address Book/ContactsViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift

High
This PR corrects a missing account object preventing the `SelectAssetViewController` from being properly presented.
Confirmed payments still worked by sending lumens to @MeghaBambra

[FIX] Unresponsive "send payment" button on the contact tab

---

BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Resources/Info.plist
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
StellarAccountService/Services/StellarAccountService+Internal.swift
StellarAccountService/Services/StellarAccountService.swift
StellarAccountService/Utilities/SecretManager.swift

High
This PR corrects the behaviour when navigating backwards after generating a mnemonic.
N/A

[FIX] Corrects back navigation behavior when creating a new wallet

---

BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

High
This PR adds support to use a timer to periodically update the order book.

[FEATURE] Adds periodic updates to the order book

---

BlockEQ/Views/MyOffersHeaderView.xib
BlockEQ/Views/OrderBookHeaderView.xib

Low
Removes use of dynamic font type for order headers. This feature is unsupported and is throwing warnings in the project.
N/A

[FIX] Warning related to using unsupported dynamic type

---

BlockEQ/Coordinators/TradingCoordinator.swift

High
This PR corrects adding an asset when on the trade screen.

[FIX] Corrects behaviour of the 'Add Asset' button on the trade selector

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Extensions/UIDevice.swift
BlockEQ/Objects/Diagnostic.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/Resources/Info.plist
BlockEQ/Utils/Strings.swift

Normal
This PR implements a `Diagnostic` object which will be used to assist users when creating issue reports inside the application. It will be used to collect:
* App Version
* OS version
* Battery state
* Hardware device
* Public Wallet Address
* How the wallet was created
* If a passphrase was used
* Email address
* Issue summary
N/A

[FEATURE] Adds a diagnostic struct to the app which will collect public data

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Coordinators/DiagnosticCoordinator.swift
BlockEQ/Coordinators/OnboardingCoordinator.swift
BlockEQ/Objects/DeviceData.swift
BlockEQ/Objects/Diagnostic+Extensions.swift
BlockEQ/Objects/Diagnostic.swift
BlockEQ/Utils/KeychainHelper.swift
BlockEQ/View Controllers/Diagnostics/DiagnosticViewController.swift
BlockEQ/Views/Cells/Diagnostics/DiagnosticDataCell.swift

WIP
This PR integrates recording how a wallet was created during creation / recovery, in order to support the diagnostic feature and passing that along during issue reports later on.
N/A
* Split Diagnostic into AppDiagnostic and WalletDiagnostic objects

[FEATURE] Implement diagnostic collection during wallet creation

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/ApplicationCoordinator.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Settings/EQSettings.swift
BlockEQ/View Controllers/Settings/IndexingViewController.swift
BlockEQ/View Controllers/Settings/IndexingViewController.xib
StellarAccountService/Operations/Misc/NodeIndexingOperation.swift
StellarAccountService/Protocols.swift
StellarAccountService/Services/StellarIndexingService.swift
StellarAccountServiceTests/Services/StellarIndexingServiceTests.swift

High
This PR adds a set of debug tools to help visualize / report what's going on during indexing in order to resolve some strange issues when trying to map `StellarEffect` objects to `StellarTransaction` objects

[FIX] Tools for debugging the StellarIndexingService and NodeIndexingOperation

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift

High
This PR corrects a compilation error due to a missing `#if DEBUG ... #endif` check.
N/A

[FIX] Corrects a compilation error in release mode

---

BlockEQ/Coordinators/AddressCoordinator.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift

Low
Updated the address resolver to use the list of exchanges from the BlockEQ API, and fall back to the local copy if necessary.
N/A

[FIX] Updated the address resolver to fetch the exchange list from the API

---

Podfile
Podfile.lock

Urgent
This PR targets the master branch of the Soneso Stellar SDK to integrate bleeding-edge changes.
N/A
N/A

Updates Podfile to use master branch of the Soneso SDK

---

BlockEQ/Data Sources/WalletDataSource.swift
BlockEQ/Utils/URLs.swift

Normal
This PR adds an easier way to switch between API environments during testing. It also corrects improperly filtered `StellarEffect` objects in the `WalletDataSource` cause by an incorrect boolean test.
N/A

[FIX] Update API endpoints to staging + correct wallet filtering

---

CHANGELOG.md

High
Updates the chagelog for v2.4.0
N/A

Update changelog for version 2.4.0

---

BlockEQ/Resources/Info.plist
CHANGELOG.md

Normal
Bumps version to 2.4.1 and updates changelog.
N/A

Update version and changelog for v2.4.1

---

Podfile.lock

Normal
Runs `pod update` on the project to update our dependencies to the latest versions.
N/A

Updates project pods

---

BlockEQ/Coordinators/AuthenticationCoordinator.swift
BlockEQ/View Controllers/Address Book/ContactsViewController.swift
BlockEQ/View Controllers/Application/AppTabController.swift
BlockEQ/View Controllers/Application/ContainerViewController.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift
BlockEQ/View Controllers/Wallet/AddAssetViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/SendAmountViewController.swift
BlockEQ/View Controllers/Wallet/SendViewController.swift
BlockEQ/View Controllers/Wallet/VerificationViewController.swift

Normal
This PR corrects issues with the keyboard not being dismissed when the PIN entry screen is presented. 
In addition to correcting when the PIN entry is presented, it also dismisses the keyboard when switching between internal view controllers.

[FIX] Fixes issue #162 (keyboard appearing on top of PIN)

---

Podfile.lock

Low
Updates pods to include latest versions.
N/A

Update project dependencies

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ.xcworkspace/contents.xcworkspacedata
StellarHub.xcodeproj/project.pbxproj

Normal
Removes the unused Kingfisher pod until we actually need it.
N/A

[FIX] Remove unused kingfisher pod

---

BlockEQ.xcodeproj/project.pbxproj

High
Adds lightweight anonymous analytics when project is built.
N/A

[FEATURE] Anonymous build analytics

---

BlockEQ.xcodeproj/project.pbxproj
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Operations/FetchAssetIconsOperation.swift
BlockEQ/Utils/CacheManager.swift

Normal
This PR improves the asset image caching by moving the code into an operation that may be enqueued. 
It also properly utilizes the default `Storage<Image>` cache that `Imaginary` provides by default.
N/A

[FEATURE] Improvements to asset icon caching

---

BlockEQ/View Controllers/Address Book/StellarContactViewController.swift
BlockEQ/View Controllers/Address Book/StellarContactViewController.xib

Normal
This PR improves the contact list by removing the editable name field for a contact, and also allows clearing the Stellar address for a contact without leaving the wallet.

[FIX] Contact UX improvement, fix removing contact Stellar address

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Wallet/WalletViewController.swift
StellarHub/Services/Account/AccountUpdateService.swift
StellarHub/Services/StellarIndexingService.swift

Normal
This PR implements a bunch of misc. adjustments to the `WalletViewController`, as well as being able to change the update interval of the `AccountUpdateService`.
N/A
* Allow activity indicator to be hidden in WalletViewController
* Small text change

[FIX] Switch between a short / long update interval if streaming

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+Extensions.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator+Settings.swift
BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift
StellarHub/Operations/Misc/NodeIndexingOperation.swift
StellarHub/Protocols.swift
StellarHub/Services/Account/AccountManagementService.swift
StellarHub/Services/Account/AccountUpdateService.swift
StellarHub/Services/CoreService.swift
StellarHub/Services/StellarIndexingService.swift
StellarHub/Services/Streaming/StreamService.swift
StellarHub/Services/TradeService.swift
StellarHub/Utilities/MulticastDelegate.swift

High
This PR corrects some inconsistencies when switching between wallets many times.
N/A

[FIX] Fix leaks and issues with updating when clearing / switching wallet

---

BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Address Book/StellarContactViewController.swift
BlockEQ/View Controllers/Address Book/StellarContactViewController.xib

High
This PR simplifies the `StellarContactViewController` and re-adds the ability to create a new contact.

[FIX] Re-adds the ability to create contacts

---

BlockEQ/Resources/Base.lproj/Localizable.strings

Low
This PR corrects a small typo in a low balance error message.
N/A

[FIX] Typo in low balance error message

---

BlockEQ/Coordinators/Application/ApplicationCoordinator+AccountExtensions.swift
StellarHub/Operations/Misc/NodeIndexingOperation.swift
StellarHub/Services/Account/AccountUpdateService.swift

High
This PR corrects a crash when transaction items get indexed.
N/A

[FIX] Crash when indexing transactions

---

BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

Normal
This PR corrects a hanging activity indicator when attempting to post a trade.
N/A

[FIX] Move prompts out of trading view controller in order to remove force unwraps

---

BlockEQ/Resources/Info.plist
CHANGELOG.md

Update changelog and bump build number

---

BlockEQ/Resources/Settings.bundle/Pods-acknowledgements.plist
Podfile.lock

High
This PR updates the following dependencies:
* [Soneso SDK](https://github.com/Soneso/stellar-ios-mac-sdk/commit/600d39b633f6227dd908a7b8b9638925a36dbd42)
* [Alamofire](https://github.com/Alamofire/Alamofire/releases/tag/4.8.1)
* [Imaginary](https://github.com/hyperoslo/Imaginary/releases/tag/4.2.0)
N/A

[FEATURE] Update upstream dependencies

---

BlockEQ/Coordinators/PaymentCoordinator.swift
BlockEQ/Extensions/UIAlertController+Prompts.swift
BlockEQ/Resources/Base.lproj/Localizable.strings
BlockEQ/View Controllers/Address Book/StellarContactViewController.swift
BlockEQ/View Controllers/Wallet/AddressEntryViewController.swift
BlockEQ/View Controllers/Wallet/InflationViewController.swift
BlockEQ/View Controllers/Wallet/ScanViewController.swift

Urgent
This PR corrects the QR code not functioning correctly.

[FIX] Correct QR code not being populated in address text fields

---

BlockEQ/Resources/Info.plist
CHANGELOG.md

Urgent
Bumping version and updating the changelog

Updates changelog and version number

---

BlockEQ/Coordinators/AuthenticationCoordinator.swift
BlockEQ/Utils/AppNavigationController.swift
BlockEQ/View Controllers/Application/AppTabController.swift
BlockEQ/View Controllers/Application/ContainerViewController.swift
BlockEQ/View Controllers/Application/LaunchViewController.swift
BlockEQ/View Controllers/Security/PinViewController.swift
BlockEQ/View Controllers/Settings/SettingsViewController.swift
BlockEQ/View Controllers/Wallet/WalletViewController.swift

Normal
This PR corrects how the status bar animates across modal pin presentations, and the core application.

[FIX] Corrects the animation behaviour of the status bar across the app

---

BlockEQ/Coordinators/Application/ApplicationCoordinator.swift
BlockEQ/Coordinators/TradingCoordinator.swift
BlockEQ/View Controllers/Trade/TradeViewController.swift

Low
This PR corrects a swiftlint warning in `TradingViewController`.

[FIX] Correct a file length warning in TradingCoordinator

---

BlockEQ/View Controllers/Wallet/MnemonicViewController.swift
BlockEQ/View Controllers/Wallet/MnemonicViewController.xib

Normal
This PR corrects an issue where the user was unable to scroll when the UIVisualEffectView was added to the view hierarchy.

[FIX] Inability to scroll when viewing mnemonic on small devices
